// This file is generated by Astro DB
declare module 'astro:db' {
	export const perfiles: import("@astrojs/db/runtime").Table<
		"perfiles",
		{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"perfiles","primaryKey":true}},"email":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"email","collection":"perfiles","primaryKey":false,"optional":false}},"password":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"password","collection":"perfiles","primaryKey":false,"optional":false}}}
	>;
	export const productos: import("@astrojs/db/runtime").Table<
		"productos",
		{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"productos","primaryKey":true}},"nombre":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"nombre","collection":"productos","primaryKey":false,"optional":false}},"desc":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"desc","collection":"productos","primaryKey":false,"optional":false}},"urlImagen":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"urlImagen","collection":"productos","primaryKey":false,"optional":false}}}
	>;
}
